SET IDENTITY_INSERT [dbo].[Categories] ON 
GO
INSERT [dbo].[Categories] ([CategoryID], [CategoryName]) VALUES (1, N'Travel')
GO
INSERT [dbo].[Categories] ([CategoryID], [CategoryName]) VALUES (2, N'Clothing')
GO
INSERT [dbo].[Categories] ([CategoryID], [CategoryName]) VALUES (3, N'Decor')
GO
INSERT [dbo].[Categories] ([CategoryID], [CategoryName]) VALUES (4, N'Fragrance')
GO
INSERT [dbo].[Categories] ([CategoryID], [CategoryName]) VALUES (5, N'Footwear')
GO
INSERT [dbo].[Categories] ([CategoryID], [CategoryName]) VALUES (6, N'Jewelery')
GO
INSERT [dbo].[Categories] ([CategoryID], [CategoryName]) VALUES (7, N'Accessories')
GO
SET IDENTITY_INSERT [dbo].[Categories] OFF
GO
SET IDENTITY_INSERT [dbo].[Products] ON 
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (1, 2, N'AppService', N'AppService Taupe Tapered Fit Formal Trousers', N'clothing.jpeg', 116, N'A pair of taupe mid-rise formal trousers, has a zip fly with a button closure and a concealed hook-and-bar closure, an adjustable.  autoflex waistband with belt loops, four pockets, and adjustable hemsOur stylist has paired these trousers with a belt. This pair of trousers does not come with a belt ', N' Red', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (2, 2, N'AppService', N'AppService Black Single-Breasted Slim Fit Formal Blazer', N'clothing.jpeg', 359, N'Black woven formal blazer, has a notched lapel, single-breasted with double button closure, long sleeves with buttoned detail on the hems, structured shoulders, two welt pockets on the front, a mock chest pocket, a double vented back hem, and has an attached lining with three built-in pockets', N' Black', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (3, 2, N'AppService', N'AppService Navy Single-Breasted Slim Fit Formal Blazer', N'clothing.jpeg', 299, N'Black woven formal blazer, has a notched lapel, single-breasted with double button closure, long sleeves with buttoned detail on the hems, structured shoulders, two welt pockets on the front, a mock chest pocket, a double vented back hem, and has an attached lining with three built-in pockets.', N' Black', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (4, 2, N'AppService', N'AppService Women Coral Pink & Orange Printed Made to Measure Printed  Dress', N'clothing.jpeg', 457, N'Coral pink and orange printed made to measure  dress. Coral pink and orange printed made to measure mai dress, has a round-neck, short sleeves,  concealed side zip closure, padded cups, has embellished detailing, attached lining with mesh detailing, flared hem', N' Pink', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (5, 2, N'AppService', N'AppService Women Coral Pink & Yellow Printed Made to Measure Printed  Dress', N'clothing.jpeg', 628, N'Coral pink and yellow printedÂ made to measure  dress Coral pink and yellow printed made to measure  dress, has a round-neck, sleeveless, has attached embellished jacket with tie-up detailing, concealed side zip closure, padded cups, attached lining with mesh detailing, flared hem', N' Yellow', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (6, 2, N'AppService', N'AppService Boys Navy Blue Regular Fit Solid Casual Shirt', N'clothing.jpeg', 699, N'Navy Blue solid casual shirt, has a spread collar, long sleeves, button placket, and curved hem', N'Blue', N'Boys')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (7, 2, N'AppService', N'AppService Girls Yellow Fit and Flare Embellished Dress', N'clothing.jpeg', 161, N'Yellow embellished woven fit and flare dress, has a round neck, short sleeves, zip closure, an attached lining, and flared hem', N' Yellow', N'Girls')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (8, 2, N'AppService', N'AppService Girls Blue Solid Jacket', N'clothing.jpeg', 118, N'Blue solid jacket, has a spread collar, 4 pockets, button closure, long sleeves, straight hem', N'Blue', N'Girls')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (9, 2, N'AppService', N'AppService Girls Peach-Coloured Floral Embroidered Fit & Flare Dress', N'clothing.jpeg', 148, N'Peach-Coloured net embroidered woven fit and flare dress with embellished detail, has a round neck, short sleeves, concealed zip closure, tie-up on the back, attached lining and flared hem', N' Red', N'Girls')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (10, 2, N'AppService', N'AppService Girls Navy Blue Washed Denim Jacket', N'clothing.jpeg', 132, N'Navy Blue washed denim jacket, has a spread collar, 4 pockets, button closure, long sleeves, straight hem, and unlined', N'Blue', N'Girls')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (11, 2, N'AppService', N'AppService Boys Red & Grey Melange Solid Varsity Jacket with Applique Detail', N'clothing.jpeg', 649, N'Red and Grey Melange solid varsity jacket, has a stand collar, snap button closure, long sleeves, straight hem, unlined', N' Red', N'Boys')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (12, 2, N'AppService', N'AppService Boys Black & Grey Embroidered Regular Fit Shorts', N'clothing.jpeg', 839, N'Black and grey embroidered, has a partially elasticated waistband, hook and bar closure, 4 pockets', N' Red', N'Boys')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (13, 2, N'AppService', N'AppService Boys Black & White Regular Fit Printed Trousers', N'clothing.jpeg', 104, N'Black and white printed mid-rise trousers, hook and bar closure, and 4 pockets', N' Black', N'Boys')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (14, 2, N'AppService', N'AppService Boys Black Regular Fit Solid Chinos', N'clothing.jpeg', 839, N'Black solid mid-rise chinos, has hook-and-bar and zip closure, 5 pockets', N' Black', N'Boys')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (15, 2, N'AppService', N'AppService Girls Navy Blue Denim Striped Pinafore Dress', N'clothing.jpeg', 153, N'Navy blue striped denim woven pinafore dress, has adjustable shoulder straps, sleeveless, concealed zip closure, and flared hem', N'Blue', N'Girls')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (16, 2, N'AppService', N'AppService Boys Navy Blue Slim Fit Printed Regular Trousers', N'clothing.jpeg', 118, N'Navy Blue printed mid-rise knitted regular trousers, button closure, zip fly and 5 pockets', N'Blue', N'Boys')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (17, 2, N'AppService', N'AppService Women Black & Yellow Floral Print Layered Top', N'clothing.jpeg', 159, N'Black and yellow printed woven layered top, has a tie-up neck, sleeveless, and button closure', N' Red', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (18, 2, N'AppService', N'AppService Your Mind Boys White Printed Round Neck T-shirt', N'clothing.jpeg', 549, N'White Printed Round Neck T-shirt,short sleeves', N' White', N'Boys')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (19, 2, N'AppService', N'AppService Your Mind Boys Black Printed Round Neck T-shirt', N'clothing.jpeg', 549, N'Black and Blue Printed T-shirt, has a round neck, short sleeves', N' Black', N'Boys')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (20, 2, N'AppService', N'AppService Men Blue Self-Design Single-Breasted Bandhgala Suit', N'clothing.jpeg', 559, N'Blue self-design bandhgala suitBlue self-design bandhgala blazer, has a mandarin collar, single breasted with full button placket, long sleeves, three pockets, an attached lining and a double-vented back hemBlue self-design mid-rise trousers, has a zip fly with a button and a hook-and-bar closure, four pockets, a waistband with belt loops', N'Blue', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (21, 5, N'AppService', N'AppService Men Tan Brown Fisherman Leather Sandals', N'footwear.jpeg', 445, N'A pair of tan brown fisherman sandals.Leather upper with velcro closureCushioned footbed.Patterned synthetic outsole..', N' Brown', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (22, 5, N'AppService', N'AppService Men Brown Leather Formal Slip-Ons', N'footwear.jpeg', 956, N'A pair of brown square-toed formal slip-on shoes, has elasticated gussets on both sidesLeather upper, has a textured detai.lCushioned footbedTextured TPR outsole.', N' Brown', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (23, 5, N'AppService', N'AppService Men Beige Leather Derbys', N'footwear.jpeg', 112, N'A pair of round-toe beige derbys, has regular styling, lace-up detailLeather upper.Cushioned footbed.Textured and patterned outsole.', N' Beige', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (24, 5, N'AppService', N'AppService Men Brown Leather Loafers', N'footwear.jpeg', 712, N'A pair of square toe brown loafers, has regular styling, slip-on detail.Leather upperCushioned footbed.Textured and patterned outsole.', N' Brown', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (25, 5, N'AppService', N'AppService Men Tan Brown Formal Leather Oxfords', N'footwear.jpeg', 234, N'A pair of tan brown square-toed formal oxfords, has central lace-ups.Leather upper.Cushioned footbed.Textured TPU outsole, has a stacked heel.', N' Brown', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (26, 2, N'APIM', N'APIM Men Black & Grey Melange Printed Round Neck T-shirt', N'clothing.jpeg', 699, N'Black and grey melange printed T-shirt, has a round neck, and long sleeves', N' Black', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (27, 2, N'APIM', N'APIM Men Grey & Black Standard Regular Fit Checked Casual Shirt', N'clothing.jpeg', 479, N'Grey and black checked casual shirt, has a spread collar, long sleeves, button placket, curved hem, and 1 patch pocket', N' Black', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (28, 2, N'APIM', N'APIM Men Blue Solid Round Neck T-shirt', N'clothing.jpeg', 699, N'Blue solid T-shirt, has a round neck, long sleeves', N'Blue', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (29, 2, N'APIM', N'APIM Men Blue & White Standard Regular Fit Dyed Casual Shirt', N'clothing.jpeg', 599, N'Blue and white dyed casual shirt, has a spread collar, long sleeves, button placket, curved hem, and 1 patch pocket', N'Blue', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (30, 2, N'APIM', N'APIM Men Blue Regular Fit Checked Formal Trousers', N'clothing.jpeg', 119, N'Blue checked mid-rise formal trousers, has a button closure, four pockets', N'Blue', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (31, 2, N'APIM', N'APIM Men Olive Green Solid Round Neck T-shirt With Side Strip Detail', N'clothing.jpeg', 499, N'Olive green solid T-shirt, has a round neck, long sleeves With side strip details', N' Green', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (32, 2, N'APIM', N'APIM Difference of Opinion Men Grey Printed Round Neck T-shirt', N'clothing.jpeg', 499, N'Grey printed T-shirt, has a round neck, long sleeves', N' Grey', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (33, 2, N'APIM', N'APIM Men Brown Solid Slim Fit Regular Shorts', N'clothing.jpeg', 791, N'Brown solid low-rise regular shorts, has four pockets, a button closure', N' Brown', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (34, 7, N'APIM', N'APIM Women Multicoloured Printed Belt', N'accessories.jpeg', 449, N'Multicoloured printed beltReversible: No Stretchable: No Secured with a tang Warranty: 1 month', N' Red', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (35, 7, N'APIM', N'APIM BuckleUp Women Blue Textured Belt', N'accessories.jpeg', 449, N'Blue textured belt. Secured with a tang closure. Warranty 1 month', N'Blue', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (36, 7, N'APIM', N'APIM BuckleUp Women Tan Textured Belt', N'accessories.jpeg', 449, N'Tan textured beltReversible: NoStretchable: NoSecured with a tangWarranty: 1 monthWarranty provided by brand/manufacturer', N' Red', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (37, 6, N'Functions', N'AH Gold-Plated & Black Multistrand Head Chain', N'jwelery.jpeg', 431, N'Gold-plated and black multistranded head chain Secured with insert closure', N' Black', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (38, 6, N'Functions', N'AH Women Gold-Plated & White Studded Flower-Shaped studs', N'jwelery.jpeg', 267, N' Oxidised gold-plated and white flower-shaped nosepin, has studded detail  Secured with a clip-on closure ', N' White', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (39, 6, N'Functions', N'AH Gold-Toned & Yellow Classic Drop Earrings', N'jwelery.jpeg', 540, N'Gold-Toned and Yellow Classic Earrings and gold-plated Secured with a post and back', N' Yellow', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (40, 6, N'Functions', N'AH Gold-Plated & Blue Geometric Drop Earrings', N'jwelery.jpeg', 443, N'Gold-Toned and Blue Geometric Earrings, gold-plated, and has artificial stones Secured with a post and back', N'Blue', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (41, 6, N'Functions', N'AH Women Gold-Plated American Diamond & Ruby Studded Jewelry Set', N'jwelery.jpeg', 329, N'This jewellery set consists of a necklace and a pair of earringsGold-toned and ruby studded necklace secured by drawstring closureA pair of matching drop earrings, secured with post and back closure', N' Gold', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (42, 6, N'Functions', N'Functions Sterling Silver Textured Bangle', N'jwelery.jpeg', 998, N'Sterling silver textured bangle, has animal-shaped detail on the endsNote: This jewellery is handcrafted, therefore there might be slight variations from the image.', N' Red', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (43, 6, N'Functions', N'Functions Sterling Silver Statement Ring', N'jwelery.jpeg', 887, N'Sterling silver ring, has a circular detail withÂ multiple teardrop-shaped patterns', N' Silver', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (44, 6, N'Functions', N'Functions Maroon Gold-Plated Sterling Silver Hoop Earrings', N'jwelery.jpeg', 667, N'A pair of maroon gold-plated sterling silver hoop earrings, has floral detail with multiple multifaceted stone embellishments, and a jhumki dangler with a clusterÂ of beadsSecured with a stylised insert closure', N' Maroon', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (45, 6, N'Functions', N'Functions Imperial Filigree Collection Gold-Plated Sterling Silver Drop Earrings', N'jwelery.jpeg', 889, N'A pair of gold-plated sterling silver drop earrings, has a stylised dangler with cut-out detail, a faceted beaded dropSecured with a fish-hook ear wire', N' Gold', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (46, 6, N'Functions', N'Functions Sterling Silver Bangle', N'jwelery.jpeg', 879, N'Silver-toned textured bangle, has elephant-shaped detail on both the ends', N' Silver', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (47, 6, N'Functions', N'Functions Gold-Plated Sterling Silver Hoop Earrings', N'jwelery.jpeg', 994, N'A pair of gold-plated sterling silver hoop earrings, has an intricately designed base with embossed and pearl-like detail. Secured with an insert closure', N' Gold', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (48, 2, N'VisualStudio Code ', N'Alis Women Yellow & Blue Color blocked Tights', N'clothing.jpeg', 749, N'VisualStudio Code  Women  Yellow & Blue Colorblocked Tights, three-fouth length, elasticated waist', N'Blue', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (49, 2, N'VisualStudio Code ', N'VisualStudio Code  Women White Printed Top', N'clothing.jpeg', 740, N'White printed woven regular  top, has a round neck, and long sleeves', N' White', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (50, 2, N'VisualStudio Code ', N'VisualStudio Code  Off-White Sleeveless Top', N'clothing.jpeg', 999, N'Off-white pattern woven top, has a round neck, sleeveless, a curved hem, an attached lining', N' White', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (51, 2, N'VisualStudio Code ', N'VisualStudio Code  Clothing Navy Printed Casual Slim Shirt', N'clothing.jpeg', 107, N'Navy blue printed casual shirt, has a spread collar, a full button placket, two pockets, long sleeves, a curved hem', N' Navy', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (52, 2, N'VisualStudio Code ', N'VisualStudio Code  Off-White Sequinned Top', N'clothing.jpeg', 699, N'Off-white top, has a round neck, short sleeves, sequinned detail along the bodice, ruffled detail along the curved hem', N' White', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (53, 4, N'VisualStudio Code ', N'VisualStudio Code  Men Platinum Eau De Toilette Perfume 100 ml', N'fragnance.jpeg', 364, N'NotesTop notes: Mandarin, bergamot, ozonic, orange, tamarind, cardamom, black pepper, clove tones and crisp mint leavesHeart notes: Spicy woody notesBase notes: Crystal amber, vanilla guaiacwood, olibanum, patchouli, sandalwood, moos', N' Platinum', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (54, 4, N'VisualStudio Code ', N'VisualStudio Code  Men Blue Eau de Toilette 125 ml', N'fragnance.jpeg', 435, N'NotesTop notes: Lemon, apple and clovesMiddle notes: Rose, lily-of-the-valley, leather and saffronBase notes: Cedar, musk, vanilla and amber', N'Blue', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (55, 4, N'VisualStudio Code ', N'VisualStudio Code  Women La Vie De Boheme EDT 75ml', N'fragnance.jpeg', 460, N'VisualStudio Code  La Vie De Boheme Eau De Toilette Strong perfumeLasts 2 to 3 hours Fresh Fragrance. Top notes: Turkish rose, sparkling pear, berries and pitahaya accord Heart notes: Red magnolia, peony, pink freesiaBase notes: dry woods, sandalwood, musk and black vanillaIt comes in a 75 ml bottle.', N'', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (56, 4, N'VisualStudio Code ', N'VisualStudio Code  Men  Eau De Toilette 90 ml', N'fragnance.jpeg', 213, N'NotesTop notes: Grapefruit, Watermelon, Pink PepperHeart notes: Cardamom, Lavendin, BasilBase notes: Vetiver, Patchouli, Moss', N'', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (57, 4, N'VisualStudio Code ', N'VisualStudio Code  Men  Eau De Toilette 90 ml', N'fragnance.jpeg', 874, N'NotesTop notes: Mojito Chords, Sparkling Grapefruit, CardamomHeart notes: Cedar, Tart Geranium, Black PepperBase notes: Vanilla, Patchouli and Leather', N'', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (58, 1, N'DOTNET', N'DOTNET Unisex Black & Grey Printed Medium Trolley Bag', N'travel.jpeg', 117, N'Black and grey printed medium trolley bag, secured with a TSA lockOne handle on the top and one on the side, has a trolley with a retractable handle on the top and four corner mounted inline skate wheelsOne main zip compartment, zip lining, two compression straps with click clasps, one zip compartment on the flap with three zip pockets ', N' Black', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (59, 1, N'DOTNET', N'DOTNET Unisex Black Large Trolley Bag', N'travel.jpeg', 173, N'Black solid large trolley bag, secured with a TSA lockOne handle on the top and one on the side, has a trolley with a retractable handle on the top and four corner mounted inline skate wheelsOne main zip compartment, zip lining, two compression straps with click clasps and one zip pocketOne exterior zip pocketWarranty: 5 years ', N' Black', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (60, 1, N'DOTNET', N'DOTNET Unisex Black Medium Trolley Bag', N'travel.jpeg', 133, N'Black solid medium trolley bag, secured with a TSA lockOne handle on the top and one on the side, has a trolley with a retractable handle on the top and four corner mounted inline skate wheelsOne main zip compartment, zip lining, two compression straps with click clasps and one zip pocketOne exterior zip pocket ', N' Black', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (61, 1, N'DOTNET', N'DOTNET Unisex Gold & White Printed Cabin Trolley Bag', N'travel.jpeg', 144, N'Gold and white printed cabin trolley bag, secured with a TSA lockOne handle on the top and one on the side, has a trolley with a retractable handle on the top and four corner mounted inline skate wheelsOne main zip compartment, zip lining, two compression straps with click clasps, one zip compartment on the flap with three zip pocketsWarranty: 5 yearsWarranty provided by Brand Owner / Manufacturer', N' White', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (62, 1, N'DOTNET', N'DOTNET Unisex Gold & White Printed Large Trolley Bag', N'travel.jpeg', 162, N'Gold and white printed large trolley bag, secured with a TSA lockOne handle on the top and one on the side, has a trolley with a retractable handle on the top and four corner mounted inline skate wheelsOne main zip compartment, zip lining , two compression straps with click clasps, one zip compartment on the flap with three zip pockets ', N' White', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (63, 1, N'DOTNET', N'DOTNET Unisex Black Large Trolley Bag', N'travel.jpeg', 139, N'Black textured large trolley bag, secured with a TSA lockOne handle on the top and one on the side, has a trolley with a retractable handle on the top and four corner mounted inline skate wheelsOne main zip compartment, an inner mesh zip compartment, two compression straps with click clasps and one zip compartment on the flap with a zip pocket ', N' Black', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (64, 1, N'DOTNET', N'DOTNET Unisex Silver Medium Trolley Bag', N'travel.jpeg', 123, N'Silver textured medium trolley bag, secured with a TSA lockOne handle on the top and one on the side, has a trolley with a retractable handle on the top and four corner mounted inline skate wheelsOne main zip compartment, an inner mesh zip compartment ', N' Silver', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (65, 1, N'DOTNET', N'DOTNET Unisex Maroon Solid Leather Backpack with Pouch', N'travel.jpeg', 976, N'Maroon backpackPadded haul loop3 and more main compartments with zip closurePadded backZip PocketPadded shoulder strap: Padded Water-resistance: Yes       Comes with a pouch', N' Maroon', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (66, 2, N'DOTNET', N'DOTNET Women Maroon Printed Kurta with Palazzos', N'clothing.jpeg', 892, N'Maroon printed kurta with palazzos Maroon straight calf length kurta, has a round neck, three-quarter sleeves, straight hem, side slitsMaroon  Printed palazzos, has elasticated waistband, slip-on closure', N' Maroon', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (67, 4, N'DOTNET', N'DOTNET Men To Be The King Eau De Toilette 125 ml', N'fragnance.jpeg', 346, N'To Be The King Eau De ToiletteÂ ', N'', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (68, 6, N'DOTNET', N'DOTNET Gold-Toned Square Cufflinks', N'jwelery.jpeg', 539, N'A pair of gold-toned square solid cufflinks', N' Gold', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (69, 6, N'DOTNET', N'DOTNET Gold-Toned Geometric Cufflinks', N'jwelery.jpeg', 539, N'A pair of gold-toned and blue geometric printed cufflinksComes in a signature case', N' Gold', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (70, 6, N'DOTNET', N'DOTNET Gold-Toned & Black Round Cufflinks', N'jwelery.jpeg', 539, N'A pair of gold-toned and black round solid cufflinks', N' Black', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (71, 6, N'DOTNET', N'DOTNET Gold-Toned Geometric Cufflinks', N'jwelery.jpeg', 539, N'A pair of gold-toned geometric textured cufflinksComes in a signature case', N' Gold', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (72, 6, N'DOTNET', N'DOTNET Silver-Toned Geometric Cufflinks', N'jwelery.jpeg', 539, N'A pair of silver-toned geometric solid cufflinksComes in a signature case', N' Silver', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (73, 3, N'Functions', N'Functions Gold-Toned & White Solid Handcrafted Table Lamp with Shade', N'decor.jpeg', 162, N'Type: Handcrafted Table Lamp with Shade.Colour: Gold-Toned and whitePattern: Solid.Shape: FrustumShade material: Fabric.Base material: Aluminium.', N' White', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (74, 3, N'Functions', N'Functions Gold-Toned Solid Handcrafted Table Lamp with Shade', N'decor.jpeg', 183, N'Type: Handcrafted Table Lamp with Shade.Colour: Gold-Toned.Pattern: SolidShape: Frustum.Shade material: FabricBase material: Aluminium.Switch Type: Toggle Button', N' Gold', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (75, 3, N'Functions', N'Functions Gold-Toned & White Solid Handcrafted Table Lamp with Shade', N'decor.jpeg', 173, N'Type: Handcrafted Table Lamp with Shade.Colour: Gold-Toned and white.Pattern: SolidShape: Frustum.Shade material: FabricBase material: Aluminium.Bulb Holder Type: E27Switch Type: Toggle Button.Comes with bulb', N' White', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (76, 3, N'Functions', N'Functions Gold-Toned & Navy Blue Solid Handcrafted Table Lamp with Shade', N'decor.jpeg', 189, N'Type: Handcrafted Table Lamp with Shade.Colour: Gold-Toned and navy blue.Pattern: SolidShape: Frustum.Shade material: FabricBase material: Aluminium.Bulb Holder Type: E27Switch Type: Toggle Button.Comes with bulb', N'Blue', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (77, 3, N'Functions', N'Functions Gold-Toned & Navy Blue Solid Handcrafted Table Lamp with Shade', N'decor.jpeg', 173, N'Type: Handcrafted Table Lamp with Shade.Colour: Gold-Toned and navy blue.Pattern: SolidShape: Frustum.Shade material: Fabric.Base material: Aluminium.Bulb Holder Type: E27Switch Type: Toggle ButtonComes with bulb', N'Blue', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (78, 3, N'Functions', N'Functions Gold-Toned & White Solid Handcrafted Table Lamp with Shade', N'decor.jpeg', 183, N'Type: Handcrafted Table Lamp with Shade.Colour: Gold-Toned and white.Pattern: SolidShape: Frustum.Shade material: Fabric.Base material: Aluminium.Bulb Holder Type: E27Switch Type: Toggle Button.Comes with bulb', N' White', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (79, 4, N'GitHub', N'GitHub Women Splendida  Eau De Parfum 100 ml', N'fragnance.jpeg', 109, N'Top notes: Violet Leaves absolute, Heliotrope. Heart notes: Orris abs, Mimosa absBase notes: Tonka beans, Heart of Vetiver, Sandalwood ess', N'', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (80, 4, N'GitHub', N'GitHub Women  Crystalline Eau De Toilette 40 ml', N'fragnance.jpeg', 565, N'Airy Bamboo and Exotic Asian Fruit NashiHeart', N'', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (81, 4, N'GitHub', N'GitHubi Women Paraiba Eau De Toilette Perfume 65 ml', N'fragnance.jpeg', 700, N'GitHub Omnia  Eau De Toilette captures the myriad scents of floral, fruity and tropical notes. Features:  passion fruit, bitter orange. Heart notes: Passion flower and Brazilian gardenia', N'', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (82, 4, N'GitHub', N'GitHub Goldea Women Night Eau De Parfum 75 ml', N'fragnance.jpeg', 975, N'The Roman Night Eau De Parfum', N' Gold', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (83, 4, N'GitHub', N'GitHub Women Rose Goldea Eau De Perfume 90 ml', N'fragnance.jpeg', 109, N'Rose Goldea Eau De Parfum', N' Gold', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (84, 4, N'GitHub', N'GitHub Splendida  Eau De Parfum 50 ml', N'fragnance.jpeg', 765, N'Mandarin Orange and Blackberry. Heart notes: Damask Rose. Base notes: Patchouli, Sandalwood, Vetiver and Musk', N' Rose', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (85, 4, N'GitHub', N'Goldea Edp 90Ml', N'fragnance.jpeg', 109, N'Inspired by gold and light, GitHubgari presents this Edt, which has begins with the top notes of crystal musk, orange blossom, raspberry, and bergamot. ', N' Gold', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (86, 4, N'GitHub', N'GitHub Men Black Eau De Toilette 40 ml', N'fragnance.jpeg', 234, N'GitHub gari presents this Black EDT that will ensure a reviving and invigorating fragranceThis EDT has a subtle background tobacco-like note, leading the way to a sweet and a tad creamy heart along with rummy and woody notes', N' Black', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (87, 5, N'GitHub', N'GitHub Men Tan Brown Flat Boots', N'footwear.jpeg', 581, N'A pair of round-toe tan brown flat boots, has regular styling, lace-up detail. Synthetic Leather upper Cushioned footbedTextured and patterned outsole', N' Brown', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (88, 5, N'GitHub', N'GitHub Men Grey Sneakers', N'footwear.jpeg', 234, N'A pair of round-toe grey sneakers, has regular styling, lace-up detail .Synthetic upperCushioned footbedTextured and patterned outsole', N' Grey', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (89, 5, N'GitHub', N'GitHub Men Black Sneakers', N'footwear.jpeg', 764, N'A pair of round-toe black sneakers, has regular styling, lace-up detail. Synthetic upper Cushioned footbed Textured and patterned outsole', N' Black', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (90, 2, N'AppService', N'AppService Women Pink Alexa Super Skinny Fit High-Rise Clean Look Stretchable Cropped Jeans', N'clothing.jpeg', 899, N'Pink coloured wash 5-pocket high-rise cropped jeans, clean look, no fade, has a button and zip closure, and waistband with belt loops', N' Pink', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (91, 2, N'AppService', N'AppService Women Burgundy Alexa Super Skinny Fit High-Rise Clean Look Stretchable Ankle Jeans', N'clothing.jpeg', 899, N'Burgundy coloured wash 5-pocket high-rise jeans, clean look, no fade, has a button and zip closure, and waistband with belt loops', N' Burgundy', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (92, 2, N'AppService', N'AppService Women Blue Adora Skinny Fit Mid-Rise Clean Look Stretchable Ankle Jeans', N'clothing.jpeg', 119, N'Blue medium wash 5-pocket mid-rise jeans, clean look, heavy fade, has a button and zip closure, and waistband with belt loops', N'Blue', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (93, 5, N'AppService', N'AppService Women Maroon Solid Suede Finish Open Toe Flats', N'footwear.jpeg', 334, N'A pair of maroon solid open-toed flats, has regular styling, no back strap detailSuede upperCushioned footbed. Textured and patterned outsole', N' Maroon', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (94, 5, N'AppService', N'AppService Women Beige Solid Open Toe Flats', N'footwear.jpeg', 551, N'A pair of beige open-toed flats, has regular styling, buckle detailSynthetic upper. Cushioned footbedTextured and patterned outsole', N' Beige', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (95, 5, N'AppService', N'AppService Women Green Solid Open Toe Flats', N'footwear.jpeg', 335, N'A pair of green open-toed flats, has regular styling, no back strap detailSynthetic upper.Cushioned footbedTextured and patterned outsole', N' Green', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (96, 2, N'LogicApps', N'LogicApps Boys Red Printed Pyjamas', N'clothing.jpeg', 389, N'Red printed pyjamas Red straight above knee t-shirt, has a mandarin collar, long sleeves, straight hem, side slits. Red  Solid pyjamas, has elasticated waistband, slip-on closure', N' Red', N'Boys')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (97, 2, N'LogicApps', N'LogicApps  Boys Peach-Coloured & Brown Solid  Pyjamas', N'clothing.jpeg', 539, N'Peach-Coloured and brown solid kurta with pyjamasBrown straight above knee kurta, has a mandarin collar, long sleeves, curved hem, side slitsBrown Solid pyjamas, has elasticated waistband, slip-on closureComes with peach coloured self design jacket has mandarin collar, button closure, sleeveless', N' Red', N'Boys')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (98, 2, N'LogicApps', N'LogicApps Girls Pink A-Line Organic Cotton Sustainable Dress', N'clothing.jpeg', 499, N'Pink printed knitted A-line dress, has a round neck, short sleeves, flared hem', N' Pink', N'Girls')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (99, 3, N'LogicApps', N'LogicApps Beige & Black Indian Art Printed Set of 4 Ceramic Bowls', N'decor.jpeg', 146, N'Type: Bowls Pattern: Printed Finish: Matte Material: Ceramic', N' Black', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (100, 3, N'LogicApps', N'LogicApps Set of 3 Blue & Off-White Handpainted Kitchen Storage Jars with Lids', N'decor.jpeg', 311, N'Set of 3 Blue & Off-White Handpainted Kitchen Storage Jars with Lids Pattern: Printed Finish: Glossy Material: Ceramic', N'Blue', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (101, 3, N'LogicApps', N'LogicApps Set Of 5 Handcrafted Ceramic Cups', N'decor.jpeg', 865, N'Set Of 5 Ceramic Cups Pattern: Printed Finish: Glossy Material: Ceramic Features: Handcrafted', N'', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (102, 5, N'LogicApps', N'Eli Women Black & Blue Woven Design Heels', N'footwear.jpeg', 123, N'A pair of black, blue, and beige open toe heels, has regular styling, backstrap detail. Synthetic upper with woven design Cushioned footbedTextured and patterned outsole, has a block heel', N'Blue', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (103, 3, N'LogicApps', N'LogicApps Set of 6 Mustard & Blue Printed Table Placemats', N'decor.jpeg', 899, N'Freesia, incense and chinese osmanthus.Heart Notes: Tuberose, lily, peony and orris root.Base Notes:Tahitian vetiver, musk and cashmere wood', N'Blue', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (104, 3, N'LogicApps', N'LogicApps  Set of 6 Multicoloured Printed Table Placemats', N'decor.jpeg', 899, N'Set content: 6 table mats.Shape: Rectangle.Colour: MulticolouredPattern: Printed.Suitable For: 6 seater table.Material: Cotton', N' Red', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (105, 3, N'LogicApps', N'LogicApps Set of 6 Printed Table Placemats', N'decor.jpeg', 899, N'Set content: 6 table mats Shape: Rectangle Colour: Pink and blue Pattern: Printed Suitable For: 6 seater table Material: Cotton ', N'', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (106, 3, N'LogicApps', N'LogicApps Set of 6 Yellow & Blue Printed Table Placemats', N'decor.jpeg', 899, N'Set content: 6 table mats Shape: Rectangle Colour: Yellow and blue.Pattern: Printed Suitable For: 6 seater table Material: Cotton ', N'Blue', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (107, 3, N'LogicApps', N'LogicApps Blue & Green Printed Wooden Open Dry Bin', N'decor.jpeg', 999, N'Set content: 1 open dry binColour: Blue and green.Pattern: Floral printShape: Rectangular', N'Blue', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (108, 3, N'LogicApps', N'LogicApps Set of 4 Multicoloured Printed Table Placemats', N'decor.jpeg', 799, N'Set content: 4 table matsShape: Rectangle.Colour:multicoloured.Pattern: Printed.Suitable For: 4 seater table.Material: Cotton', N' Red', N'Unisex')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (109, 2, N'VisualStudio', N'VisualStudio Men Maroon Striped Round Neck T-shirt', N'clothing.jpeg', 699, N'Maroon and Grey striped T-shirt, has a round neck, and long sleeves', N' Maroon', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (110, 2, N'VisualStudio', N'VisualStudio Men Navy Blue & Red Slim Fit Checked Casual Shirt', N'clothing.jpeg', 699, N'Navy Blue and red checked casual shirt, has a spread collar, long sleeves, button placket,  curved hem, one patch pocket', N'Blue', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (111, 2, N'VisualStudio', N'VisualStudio Men White & Navy Blue Slim Fit Printed Casual Shirt', N'clothing.jpeg', 699, N'White and navy blue printed casual shirt, has a spread collar, short sleeves, button placket,  curved hem, one patch pocket', N'Blue', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (112, 2, N'VisualStudio', N'VisualStudio Men Brown & Off-White Slim Fit Printed Casual Shirt', N'clothing.jpeg', 759, N'Brown and off-white printed casual shirt, has a spread collar, long sleeves, button placket,  curved hem, one patch pocket', N' White', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (113, 2, N'VisualStudio', N'VisualStudio Men Blue Slim Fit Checked Casual Shirt', N'clothing.jpeg', 719, N'Blue checked casual shirt, has a spread collar, long sleeves, button placket,  curved hem, one patch pocket', N'Blue', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (114, 2, N'VisualStudio', N'VisualStudio Men Brown Tapered Fit Solid Regular Trousers', N'clothing.jpeg', 664, N'Brown solid regular trousers regular trousers', N' Red', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (115, 2, N'VisualStudio', N'VisualStudio Men Green Printed Polo Collar T-shirt', N'clothing.jpeg', 629, N'Green printed T-shirt, has a polo collar, and short sleeves', N' Green', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (116, 2, N'VisualStudio', N'VisualStudio Men Red Slim Fit Checked Casual Shirt', N'clothing.jpeg', 752, N'Red checked casual shirt, has a spread collar, long sleeves, button placket,  curved hem, one patch pocket', N' Red', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (117, 5, N'VisualStudio', N'VisualStudio Women Brown Solid Cushioned Mules', N'footwear.jpeg', 624, N'A pair of pointed closed toe brown mules with comfort lining and foam cushioned footbed for your work-from-home needs. It has regular styling, and closed back.Synthetic upper.Foam Cushioned footbedTextured and patterned outsole', N' Brown', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (118, 5, N'VisualStudio', N'VisualStudio Women Red Cushioned Loafers', N'footwear.jpeg', 532, N'A pair of round closed toe red loafers with comfort lining and foam cushioned footbed for your work-from-home needs. It has regular styling, and closed back.Synthetic upper.Foam Cushioned footbed.Textured and patterned outsole', N' Red', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (119, 5, N'VisualStudio', N'VisualStudio Women Tan Brown Cushioned Slip-on Shoes', N'footwear.jpeg', 763, N'A pair of pointed closed toe tan brown slip-on shoes with cushioned footbed and comfortable lining, has regular styling, and closed back.Synthetic upper.Foam Cushioned footbed.Textured and patterned outsole', N' Brown', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (120, 5, N'VisualStudio', N'VisualStudio Women Green Cushioned Slip-Ons', N'footwear.jpeg', 457, N'A pair of pointed toe green slip-ons with cushioned footbed, has regular styling, slip-on detail.Synthetic Suede upper.Foam cushioned footbed.Textured and patterned outsole', N' Green', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (121, 5, N'VisualStudio', N'VisualStudio Women Black Textured Cushioned Flats', N'footwear.jpeg', 642, N'A pair of black pointed toe cushioned flats, has regular styling, slip-on detail.Synthetic upper.Cushioned footbedTextured and patterned outsole', N' Red', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (122, 4, N'VisualStudio', N'VisualStudio Mic Women  Amber Eau de Parfum 100ml', N'fragnance.jpeg', 236, N'  Amber Eau de Parfum.Fragrance Notes:Top notes - amber.Heart notes - sandalwood.Base - white flowers', N'', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (123, 4, N'VisualStudio', N'VisualStudio Mic Extreme Blue For Men Edt 70 ml', N'fragnance.jpeg', 556, N'What it is:Extreme Blue For Men Ed.What it does:Masculine and sensuous at the same time is this Blue Eau De Toilette .. Exuding unmatched freshness, this EDT is a must-have in your collection of fragrances. Available in a 70 ml pack, this EDT has top notes of bergamot, spicy pink pepper and invigorating cardamom.', N'Blue', N'Men')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (124, 4, N'VisualStudio', N'VisualStudio Mic Women Eau de Toilette 50 ml', N'fragnance.jpeg', 876, N'Freesia, incense and chinese osmanthus.Heart Notes: Tuberose, lily, peony and orris root.Base Notes:Tahitian vetiver, musk and cashmere wood', N'', N'Women')
GO
INSERT [dbo].[Products] ([ProductID], [CategoryID], [ProductBrand], [ProductName], [ProductImage], [ProductPrice], [ProductDescription], [ProductColor], [ProductGender]) VALUES (125, 7, N'A.Datum', N'GreenBlue Regular Fit Solid Chinos', N'accessories.jpeg', 764, N'Greenish Blue solid mid-rise chinos, has hook-and-bar and zip closure, 5 pockets and tie laces', N'Green', N'Men')
GO
SET IDENTITY_INSERT [dbo].[Products] OFF
GO
SET IDENTITY_INSERT [dbo].[Orders] ON 
GO
INSERT [dbo].[Orders] ([OrderID], [ProductID], [ProductDesc], [CatID], [Quantity], [TotalPrice], [CatName]) VALUES (1, 80, N'GitHub Women  Crystalline Eau De Toilette 40 ml', 4, 1, 565, N'Fragrance')
GO
INSERT [dbo].[Orders] ([OrderID], [ProductID], [ProductDesc], [CatID], [Quantity], [TotalPrice], [CatName]) VALUES (2, 97, N'LogicApps  Boys Peach-Coloured ', 2, 1, 539, N'Clothing')
GO
INSERT [dbo].[Orders] ([OrderID], [ProductID], [ProductDesc], [CatID], [Quantity], [TotalPrice], [CatName]) VALUES (3, 111, N'VisualStudio Men White ', 2, 1, 699, N'Clothing')
GO
INSERT [dbo].[Orders] ([OrderID], [ProductID], [ProductDesc], [CatID], [Quantity], [TotalPrice], [CatName]) VALUES (4, 65, N'DOTNET Unisex Maroon Solid Leather Backpack with Pouch', 1, 1, 976, N'Travel')
GO
SET IDENTITY_INSERT [dbo].[Orders] OFF
GO
